const mongoose = require('mongoose');


const InventorySchema = mongoose.Schema({
  email: { type: String },
  supplierName: { type: String },
  drugName: { type: String },
  composition: { type: String },
  drugType: { type: String },
  batchID: { type: String },
  quantity: { type: Number },
  supplierLicenseNumber: {type: String},
  drugLicenseNumber: {type: String},
  totalStripsCount: { type: Number },
  totalTabletsCount: { type: Number },
  expireDate: { type: Date },
  mrp: { type: Number },
  rate: { type: Number },
  amount: { type: Number },
  free: { type: Number },
  scheduleType: { type: String },
  manufacturer: { type: String },
  orderID: { type: String },
  barCode: { type: String },
  licenseNumber: { type: String },
  packageType: { type: String },
  packSize: { type: String },
  shelf: { type: String },
  gst: { type: Number },
  cGST: { type: Number },
  sGST: { type: Number },
  iGST: { type: Number },
  hsnCode: { type: String },
  discount: { type: String },
  box: { type: String },
  thresholdValue: { type: Number },
  previousQuantity:{type:String},
  createdby: { type: String },
  createdUserRole: [{ type: String }],
  createdDate: { type: Date },
  lastUPdatedDate: { type: Date },
});
  const Inventory = mongoose.model('Inventory', InventorySchema);
module.exports = Inventory;